"""empty message

Revision ID: 4528e309da01
Revises: 764684548e87
Create Date: 2020-07-22 03:43:37.685655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4528e309da01'
down_revision = '764684548e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
