"""empty message

Revision ID: 796838629ea3
Revises: 907fc4755a4c
Create Date: 2020-07-21 04:10:06.388967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '796838629ea3'
down_revision = '907fc4755a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
